site_name: ZWiley的随记
site_description: ZWiley的随记
site_author: ZWiley
site_url: https://zwiley.github.io/mybook/

theme:
    name: material
    features:
        - instant
    font:
        code: Ubuntu Mono
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    hljs_style: github
    prev_next_buttons_location: bottom
    navigation_depth: 6
    sticky_navigation: False
    language: 'zh'

repo_name: 'GitHub'
repo_url: https://github.com/zwiley/mybook/

extra_javascript:   
    - 'js/extra.js'
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: true
      linenums: false
  - sane_lists
  - mdx_math:
      enable_dollar_delimiter: True
  - smarty
  - toc:
      permalink: True       
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
    - 简介: 'index.md'
    - C++: 
      - C++ STL: '基础语言/STL.md'
      - C++编译底层: '基础语言/C++编译底层.md'
      - C++基础知识: '基础语言/C++基础知识.md'
      - C++智能指针: '基础语言/C++智能指针_异常机制_强制转换_RTTI.md'
      - C++面向对象: '基础语言/C++面向对象.md'
    - 计算机基础: 
      - 操作系统: '计算机基础知识/操作系统.md'
      - 计算机网络: '计算机基础知识/计算机网络.md'
      - 数据结构: '计算机基础知识/数据结构.md'
      - 海量数据处理: '计算机基础知识/海量数据处理.md'
    - 基本手写代码: 
      - 常见基本代码: '基本手写代码/基本手写代码题目.md'
    - 项目基础知识: 
      - Linux系统编程及基本命令: '项目基础知识/Linux系统编程及基本命令.md'
      - MySQL: '项目基础知识/MySQL.md'
      - Redis: '项目基础知识/Redis.md'
      - Socket编程: '项目基础知识/Socket编程.md'
    - webserver项目:
      - 0 项目概述: 'webserver/0 项目概述.md'
      - 1 线程同步机制封装类: 'webserver/1 线程同步机制封装类.md'
      - 2 半同步半反应堆线程池（上）: 'webserver/2 半同步半反应堆线程池（上）.md'
      - 3 半同步半反应堆线程池（下）: 'webserver/3 半同步半反应堆线程池（下）.md'
      - 4 http连接处理（上）: 'webserver/4 http连接处理（上）.md'
      - 5 http连接处理（中）: 'webserver/5 http连接处理（中）.md'
      - 6 http连接处理（下）: 'webserver/6 http连接处理（下）.md'
      - 7 定时器处理非活动连接（上）: 'webserver/7 定时器处理非活动连接（上）.md'
      - 8 定时器处理非活动连接（下）: 'webserver/8 定时器处理非活动连接（下）.md'
      - 9 日志系统（上）: 'webserver/9 日志系统（上）.md'
      - 10 日志系统（下）: 'webserver/10 日志系统（下）.md'
      - 11 数据库连接池: 'webserver/11 数据库连接池.md'
      - 12 常见问题: 'webserver/12 常见问题.md'
      - 13 项目梳理: 'webserver/13 项目梳理.md'
      - 14 项目问题汇总: 'webserver/14 项目问题汇总.md'
    - 源码:
      - 源码阅读: '源码阅读_sourcecode/README.md'
      - Muduo: 
        - base: 
            - 时间_原子操作_异常 : 'Muduo/base/1. 时间_原子操作_异常.md'
            - 线程 : 'Muduo/base/2. 线程.md'
            - 线程2 : 'Muduo/base/3. 线程2.md'
            - 日志 : 'Muduo/base/4. 日志.md'
        - net:
            - EventLoop : 'Muduo/net/1. EventLoop.md'
            - 连接时序 : 'Muduo/net/2. 连接时序.md'
            - 关闭时序 : 'Muduo/net/3. 关闭时序.md'
            - Buffer : 'Muduo/net/4. Buffer.md'
            - callback : 'Muduo/net/5. callback.md'
            - Client: 'Muduo/net/6. Client.md'
        - 服务器方案设计: 'Muduo/0 服务器方案设计.md'
        - 基础知识: 'Muduo/1 基础知识.md'
        - 总体解析: 'Muduo/2 总体解析.md'
        - muduo详细运行流程: 'Muduo/3 muduo详细运行流程.md'
        - muduo中的定时器: 'Muduo/4 muduo中的定时器.md'
        - muduo中的线程: 'Muduo/5 muduo中的线程.md'
        - muduo中的回调: 'Muduo/6 muduo中的回调.md'
    - 数据库:
      - Getting started with impala: 'database/getting_started_with_impala.md'
      - mysql必知必会: 'database/mysql必知必会.md'
      - mysql性能调优与架构实践: 'database/mysql性能调优与架构实践.md'
      - Mysql技术内幕InnoDB存储引擎: 'database/Mysql技术内幕InnoDB存储引擎.md'
      - Redis实战: 'database/redis实战.md'
      - Redis深度历险核心原理和应用实践: 'database/redis深度历险核心原理和应用实践/book.md'
      - redis设计与实现: 'database/redis设计与实现.md'
      - 七周七数据库: 'database/七周七数据库.md'
      - 深入浅出mysql: 'database/深入浅出mysql.md'
      - 高性能mysql第三版: 'database/高性能mysql第三版.md'  
    - 代码:
      - 代码大全: 'code/代码大全.md'
      - 代码的未来: 'code/代码的未来.md'
      - 基本功: 'code/基本功.md'
      - 敏捷技能修炼: 'code/敏捷技能修炼.md'
      - 程序员应该知道的97件事: 'code/程序员应该知道的97件事.md'
      - 编写可读代码的艺术: 'code/编写可读代码的艺术.md'
      - 编程匠艺: 'code/编程匠艺.md'
      - 领域驱动设计: 'code/领域驱动设计.md'
      - codelife_不止代码: 'code/codelife_不止代码.md'
    - 调试技术:
      - 软件调试修炼之道: 'debug/软件调试修炼之道/book.md'
      - Effective Debugging: 'debug/Effective_Debugging.md'
    - 前端:
      - CSS_The_Missing_Manual: 'frontend/CSS_The_Missing_Manual.md'
      - reactjs小书: 'frontend/reactjs_小书.md'
      - ES6标准入门: 'frontend/es6标准入门.md'
      - jquery_pocket_reference: 'frontend/jquery_pocket_reference.md'
      - 深入理解bootstrap: 'frontend/深入理解bootstrap.md'
    - golang:
      - 1 The Go Programming Language: 'golang/1_the_go_programming_lauguage.md'
      - 2 The Go Programming Language: 'golang/2_the_go_programming_lauguage.md'
      - 3 The Go Programming Language: 'golang/3_the_go_programming_lauguage.md'
      - Build Web Application With Golang: 'golang/build-web-application-with-golang.md'
      - Go101: 'golang/go101/book.md'
      - Network Programming with go: 'golang/network-programming-with-go/book.md'
      - Building Microservices With Go: 'golang/building-microservices-with-go/book.md'
      - Building Restful Web Services with Go: 'golang/building_restful_web_services_with_go/book.md'
      - Concurrency In Go: 'golang/concurrency-in-go/concurrency_in_go.md'
      - Go In Action(Go 实战): 'golang/go_in_action(go语言实战).md'
      - Go学习笔记语言详解: 'golang/go语言学习笔记语言详解.md'
      - Go学习笔记源码剖析: 'golang/go语言学习笔记源码剖析.md'
      - go语言编程: 'golang/go语言编程.md'
      - go book: 'golang/the_way_to_go/book.md'
      - advanced-go-programming: 'golang/advanced-go-programming-book/advanced-go-programming.md'
      - go-build-web-applications: 'golang/go-build-web-applications/module1/go-build-web-applications/go-build-web-applications.md'
    - python:
      - Fluent Python: 'python/fluent_python.md'
      - Python Microservices Development: 'python/Python_Microservices_Development.md'
      - High Performance Python: 'python/high_performance_python.md'
      - Python网络编程: 'python/python_网络编程.md'
    - java:
      - java basic introduction: 'java/java-basic-introduction.md'
    - 网络:
      - TCP IP详解卷一: 'network/tcp_ip详解卷一/tcp_ip详解卷一.md'
    - unix/linux:
      - Linux高性能服务器编程: 'unix_linux/Linux高性能服务器编程/Linux高性能服务器编程.md'
      - unix编程艺术: 'unix_linux/unix编程艺术.md'
      - unix网络编程卷一: 'unix_linux/unix网络编程卷一.md'
      - unix编程艺术: 'unix_linux/unix编程艺术.md' 
      - UNP: 'unix_linux/unp/unp笔记.md'           
#      - APUE: 'unix_linux/APUE/APUE笔记.md'        
    - 分布式:
      - Kafka 权威指南:  '分布式/Kafka权威指南.md'
      - 分布式框架原理与应用:  '分布式/分布式框架原理与应用.md'
      - 大规模分布式存储系统: '分布式/大规模分布式存储系统.md'
      - 深入分布式缓存从原理到实践: '分布式/深入分布式缓存从原理到实践.md'
    - 搜索引擎:
      - Elasticsearch实战: '搜索引擎/Elasticsearch实战/book.md'
    - 容器:
      - 玩转Kubernets: 'devops/玩转Kubernets-CloudMan.md'
      - 第一本docker书: 'devops/第一本docker书.md'
    - 开发工具:
      - Practical Vim: '开发工具/practical_vim/practical_vim.md'
      - Vim8文本处理实战: '开发工具/vim8文本处理实战/vim8文本处理实战.md'
      - Learn vim scrpt the hard way: '开发工具/learn_vim_the_hard_way.md'
      - Pro Git: '开发工具/pro_git.md'
      - Mastering Vim: '开发工具/Mastering_vim.md'
      - Mastering Vim Quickly: '开发工具/mastering_vim_quickly.md'
    - 网站架构微服务:
      - 微服务架构设计模式: '网站架构微服务/microservices_patterns_微服务架构设计模式/book.md'
      - 从0开始学架构: '网站架构微服务/从0开始学架构/从0开始学架构.md'
      - web scalavility for startup engineers: '网站架构微服务/web_scalavility_for_startup_engineers.md'
      - design_data_instensive_application: '网站架构微服务/design_data_instensive_application.md'
      - clean_architecture: '网站架构微服务/clean_architecture.md'
      - 微服务设计: '网站架构微服务/微服务设计.md'
      - 2_design_data_instensive_application: '网站架构微服务/2_design_data_instensive_application.md'
      - 3_design_data_instensive_application: '网站架构微服务/3_design_data_instensive_application.md'
    - 软件工程/项目管理:
      - 人月神话: '软件工程_项目管理/人月神话.md'
      - 代码之殇: '软件工程_项目管理/代码之殇.md'
      - 解析极限编程: '软件工程_项目管理/解析极限编程-拥抱变化.md'
      - 项目管理修炼之道: '软件工程_项目管理/项目管理修炼之道.md'
      - 修改软件的艺术: '软件工程_项目管理/修改软件的艺术.md'
    - 运维:
      - linux集群和自动化运维: '运维/linux集群和自动化运维.md'
      - python自动化运维: '运维/python自动化运维.md'
    - 互联网:
      - 我的互联网方法论-周鸿祎: '互联网/我的互联网方法论-周鸿祎.md'
      - 用户思维: '互联网/用户思维.md'
    - 区块链:
      - 区块链技术指南: '区块链/区块链技术指南(blockchain_guide).md'
    - 技术演讲:
      - 哔哩哔哩的go微服务实战: 'lecture/Gopher/哔哩哔哩的go微服务实战/note.md'
      - go业务基础库之Error&Context: 'lecture/Gopher/Go_Error/go业务基础库之Error&Context.md'
      - Go同步和并发设计模式: 'lecture/Gopher/Go同步和并发设计模式/note.md'
      - 左耳朵耗子-我这技术二十年: 'lecture/技术演讲/左耳朵耗子-我这技术二十年.md'
    - 金融理财:
      - 定投十年: '金融理财/定投十年.md'
      - 穷查理宝典: '金融理财/穷查理宝典.md'
    - 写作:
      - 刷屏文案写作技巧: '写作/刷屏文案写作技巧.md'
    - 思维:
      - 专注力: '思维认知/专注力_化繁为简的惊人力量.md'
      - 为什么精英这样用脑不会累: '思维认知/为什么精英这样用脑不会累.md'
      - 刻意练习: '思维认知/刻意练习.md'
      - 如何想到又做到: '思维认知/如何想到又做到.md'
      - 学习之道: '思维认知/学习之道.md'
      - 学习力: '思维认知/学习力.md'
      - 批判性思维工具: '思维认知/批判性思维工具.md'
      - 程序员的思维修炼: '思维认知/程序员的思维修炼(开发认知潜能的九堂课).md'
      - 认知天性: '思维认知/认知天性.md'
      - 超效率手册: '思维认知/超效率手册.md'
      - 如何高效记忆: '思维认知/如何高效记忆.md'
      - 科学学习: '思维认知/科学学习.md'
      - 高效程序员的45个习惯: '思维认知/高效程序员的45个习惯.md'
    - 职场:
      - give and take: 'career/give_and_take.md'
      - the_effective_engineer: 'career/the_effective_engineer.md'
      - 光速成长: 'career/光速成长.md'
      - 向上管理: 'career/向上管理.md'
      - 成功动机与目标: 'career/成功动机与目标.md'
      - 番茄工作法: 'career/番茄工作法.md'
      - 聆听沟通学: 'career/聆听沟通学.md'
      - 知乎职人觉醒: 'career/知乎职人觉醒.md'
      - 知识变现: 'career/知识变现.md'
      - 聆听沟通学: 'career/聆听沟通学.md'
      - 职场动物进化手册: 'career/职场动物进化手册.md'
      - 职场解释系: 'career/职场解释系.md'
      - 请停止无效努力: 'career/请停止无效努力.md'
      - 软技能: 'career/软技能.md'
      - 高效15法则: 'career/高效15法则.md'
      - 高效清单工作法: 'career/高效清单工作法.md'
      - 程序员的自我修养: 'career/程序员的自我修养.md'
    - 心理学:
      - 一切都是童年的错吗: 'psychology/一切都是童年的错吗.md'
      - 亲密关系: 'psychology/亲密关系.md'
      - 情商: 'psychology/情商.md'
      - 逆商: 'psychology/逆商.md'
      - 拖延心理学: 'psychology/拖延心理学.md'
      - 积极心理学: 'psychology/积极心理学.md'
      - 自控力: 'psychology/自控力.md'
      - 自控力-实操篇: 'psychology/自控力-实操篇.md'
      - 自控力:和压力做朋友: 'psychology/自控力-和压力做朋友.md'
      - 活出最乐观的自己: 'psychology/活出最乐观的自己.md'
      - 改变心理学的40项研究: 'psychology/改变心理学的40项研究.md'
      - 超越自卑: 'psychology/超越自卑.md'
      - 反脆弱: 'psychology/反脆弱.md'
    - 创业:
      - Hello Startup: 'startup/hello_startup.md'
      - 斯坦福公开课如何创业: 'startup/斯坦福公开课-如何创业.md'
      - 运营其实很简单: 'startup/运营其实很简单.md'